### ISSUE TITLE
Virustotal requests no longer work

### ISSUE THREAD

**Issue by scherma** [1aN0rmus/TekDefense-Automater#17]
Recently noticed that the tool is no longer pulling down VT data. I've checked the page manually against the regex, they haven't changed anything there and the URL's still valid so I think it must not be getting the data properly. Not sure how to debug that!

**Comment by 1aN0rmus** [comment]
@scherma I put in a workaround. Download the latest sites.xml. Basically VT didn't like the way I was formatting my GET request, so I modified it to fit more what it expected. Long term, I will move this function over to the VT api, like hashes are done, but I cannot right now as VT needs the API to come in as a GET, and I currently have the API hardcoded to a POST. Will change soon. @p4r4n0y1ng I will message you on this.
