### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by sbrun** [1aN0rmus/TekDefense-Automater#22]
Hello,
For a possible next release it would be great take a tagged release in git.
In kali we have tools that monitors web pages listing release, and it works well with github pages showing git tags. If you make a tagged release we will be automatically informed and we will update the package quickly.
Thanks

**Comment by p4r4n0y1ng** [comment]
We did this (sort of) within the code itself on Automater .21 and .211 (new releases). Based on the fact that many people use the tool, but want it to be "quiet" there are command line switches required, but basically it checks MD5 of all the modules if you run a -V on the command line. You also would need a -v to make it (verbose) talk to you in stdout. It would then report if there were changes between your local and the ones here on GitHub. Also, there is a new method of keeping your XML up to date. Basically if you run a -r, Automater will check for the tekdefense.xml file here versus the one on your local machine (if there's one there) and it will download it and use it in conjunction with your sites.xml file. This ensures you keep up to date with changes here that Ian makes to the XML, but also gives you that local sites.xml file to use as well! Pretty cool! In .211 there is collision checking between the 2 XML files too, and your local wins. All in all, you'll love it I think. Thanks for this suggestion!
