### ISSUE TITLE
VirusTotal regex: always skip the first result (see solution)

### ISSUE THREAD

**Issue by ignacioj** [1aN0rmus/TekDefense-Automater#33]
This is not really an issue but only a wrong default value. I have noticed that the default value in one of the regex for virustotal is: "<entry>\}\,\s\"(.{3,20})\"....detected...true.{19,32}result....(.{11,30})....update</entry>"
I have found that the pair {11,30} is not valid for some results, i.e.:
md5: f1e090f4d1f10a7abe586d49012dbd52
[+] Detected Engines: 1
[+] Vendor | Classification: No results found
Here the problem is that the max. value 30 is too short in this case because the string is 33 characters long: "PE:Malware.Generic/QRS!1.9E2D [F]".
I would propose to change that max. value to 40 to avoid similar exceptional strings.
Thank you for this great program!

**Comment by parosterbergmedina** [comment]
This regex is also having negative effects for very short detection name, example md5 43270e8c58d428a17fd0b277483e44d8

Changing this to '<entry>\}\,\s\"(.{3,20})\"....detected...true.{19,32}result....(.{8,40})....update</entry>'  seems to do the trick.

**Comment by parosterbergmedina** [comment]
Virus names are getting longer and longer. Pushed the character limit up to 50, use case below.
MD5:9719ce372a59ff370fa5bb93d4ad85ca

**Comment by ignacioj** [comment]
The problem is that the results for 'Bkav' are the first ones. This is part of the raw answer from VirusTotal:
........{"scans": {"Bkav": {"detected": true, "version": "1.3.0.8021", "result": "W32.HfsAdware.578C", "update": "20160519"}, "TotalDefense": {"detecte........
And the regex starts with: '<entry>\}\,\........'
I have changed the regex to:
<entry>\"([^"]{1,20})\"....detected...true.{19,32}result....([^"]{8,50})....update[^\}]*\}</entry>
So far it looks like it is working.

**Comment by 1aN0rmus** [comment]
Thanks for reporting! If you want credit for the contribution, feel free to
submit a pull request and I will accept your update into the code.
